SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'N'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'R'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'K'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'K'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'B'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'AA'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'N'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'B'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.departure_time BETWEEN 0 AND 1200 AND flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'D'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT airport_1.airport_code FROM airport airport_1 WHERE airport_1.airport_code = 'M'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'N'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'N'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'N'
SELECT DISTINCT airport_1.airport_code FROM airport airport_1 WHERE airport_1.airport_code = 'M'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'N'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT airport_1.airport_code FROM airport airport_1 WHERE airport_1.airport_code = 'M'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'AA'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'AA'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'AA'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT food_service_1.meal_code,food_service_1.meal_number,food_service_1.compartment FROM food_service food_service_1 WHERE food_service_1.meal_code = 'G'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'AA'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'H'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'W'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'C'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT class_of_service_1.booking_class FROM class_of_service class_of_service_1 WHERE class_of_service_1.booking_class = 'Y'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'AA'
SELECT DISTINCT airline_1.airline_code FROM airline airline_1 WHERE airline_1.airline_code = 'LS'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'S'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'N'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.airline_code = 'T'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.from_airport = airport_1.airport_code AND airport_1.airport_code = 'P'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1,airport_service airport_service_1,city city_1 WHERE flight_1.from_airport = airport_service_1.airport_code AND airport_service_1.city_code = city_1.city_code AND city_1.city_name = 'BALTIMORE'
SELECT DISTINCT flight_1.flight_id FROM flight flight_1 WHERE flight_1.flight_id = flight_fare_1.flight_id AND flight_fare_1.fare_id = fare_1.fare_id AND fare_1.fare_basis_code = 'F'
